[package]
name = "zk100_proof_io"
version = "0.1.0"
edition = "2024_07"

[dependencies]
zk100_vm = { path = "../vm" }

[lib]

[cairo]
enable-gas = false

[dev-dependencies]
assert_macros = "2.12.0"

[scripts]
test = "echo 'Tests would run here with cairo-test or snforge if installed'"